version: 2

sphinx:
    configuration: doc/source/conf.py

python:
   version: "3.10"
   install:
   - requirements: requirements.txt
   - requirements: requirements-docs.txt
   - method: pip
     path: .
