version: 2

submodules:
  include: all

sphinx:
    configuration: doc/source/conf.py

python:
   version: "3.8"
   install:
   - requirements: requirements.txt
   - requirements: requirements-docs.txt
   - method: pip
     path: .
