ignore:
    - arviz/tests/

codecov:
    notify:
        after_n_builds: 6

comment:
    behavior: default
    branches:
        - "main"

coverage:
  status:
    project:
      default:
        target: auto
        threshold: 2%

    patch:
      default:
        target: 75%
