ignore:
    - arviz/tests/

codecov:
    notify:
        after_n_builds: 4

comment:
    behavior: new
    after_n_builds: 4
    branches:
        - "master"

coverage:
  status:
    project:
      default:
        target: auto
        threshold: 2%

    patch:
      default:
        target: 75%
