ignore:
    - arviz/tests/

codecov:
    notify:
        after_n_builds: 5

comment:
    behavior: new
    after_n_builds: 5
    branches:
        - "master"

coverage:
  status:
    project:
      default:
        target: auto
        threshold: 2%
        base: parent

    patch:
      default:
        target: 75%
